# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleStation',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u5b57')),
                ('address', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='\u5730\u5740')),
                ('lon', models.FloatField(verbose_name='\u706b\u661f\u5ea7\u6807\u7cfb-\u7ecf\u5ea6')),
                ('lat', models.FloatField(verbose_name='\u706b\u661f\u5ea7\u6807\u7cfb-\u7eac\u5ea6')),
                ('bdlon', models.FloatField(verbose_name='\u767e\u5ea6\u5ea7\u6807\u7cfb-\u7ecf\u5ea6')),
                ('bdlat', models.FloatField(verbose_name='\u767e\u5ea6\u5ea7\u6807\u7cfb-\u7eac\u5ea6')),
                ('num', models.IntegerField(blank=True, default=None, null=True, verbose_name='\u9501\u8f66\u5668\u6570')),
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='code')),
                ('localcode', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='localcode')),
                ('bikenum', models.IntegerField(blank=True, default=None, null=True, verbose_name='\u53ef\u501f\u8f66\u6570')),
                ('emptynum', models.IntegerField(blank=True, default=None, null=True, verbose_name='\u53ef\u8fd8\u8f66\u6570')),
                ('updatetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u81ea\u884c\u8f66\u7f51\u70b9',
                'verbose_name_plural': '\u81ea\u884c\u8f66\u7f51\u70b9',
            },
        ),
        migrations.CreateModel(
            name='StationStatus',
            fields=[
                ('statuscode', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='statuscode')),
                ('status', models.CharField(max_length=50, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u7f51\u70b9\u72b6\u6001',
                'verbose_name_plural': '\u7f51\u70b9\u72b6\u6001',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zonecode', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='zonecode')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u5b57')),
            ],
            options={
                'verbose_name': '\u533a\u57df',
                'verbose_name_plural': '\u533a\u57df',
            },
        ),
        migrations.AddField(
            model_name='bicyclestation',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beijingbicycle.StationStatus', verbose_name='\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='bicyclestation',
            name='zone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beijingbicycle.Zone', verbose_name='\u533a\u57df'),
        ),
    ]
