# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beijingbicycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u5b57')),
                ('address', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='\u5730\u5740')),
                ('lon', models.FloatField(verbose_name='\u706b\u661f\u5ea7\u6807\u7cfb-\u7ecf\u5ea6')),
                ('lat', models.FloatField(verbose_name='\u706b\u661f\u5ea7\u6807\u7cfb-\u7eac\u5ea6')),
                ('bdlon', models.FloatField(verbose_name='\u767e\u5ea6\u5ea7\u6807\u7cfb-\u7ecf\u5ea6')),
                ('bdlat', models.FloatField(verbose_name='\u767e\u5ea6\u5ea7\u6807\u7cfb-\u7eac\u5ea6')),
                ('num', models.IntegerField(blank=True, default=None, null=True, verbose_name='\u9501\u8f66\u5668\u6570')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('localcode', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='localcode')),
                ('updatetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('version', models.IntegerField(verbose_name='\u7248\u672c\u53f7')),
            ],
            options={
                'verbose_name': '\u5b98\u7f51\u4fee\u6539\u65e5\u5fd7\u8868',
                'verbose_name_plural': '\u5b98\u7f51\u4fee\u6539\u65e5\u5fd7\u8868',
            },
        ),
        migrations.CreateModel(
            name='ManageLog',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u65e5\u5fd7\u5b57\u5178\u8868',
                'verbose_name_plural': '\u65e5\u5fd7\u5b57\u5178\u8868',
            },
        ),
        migrations.AddField(
            model_name='logs',
            name='manage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beijingbicycle.ManageLog', verbose_name='\u7ba1\u7406'),
        ),
        migrations.AddField(
            model_name='logs',
            name='zone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='beijingbicycle.Zone', verbose_name='\u533a\u57df'),
        ),
    ]
