# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beijingbicycle', '0002_auto_20160903_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicyclestation',
            name='bdlat',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='\u767e\u5ea6\u5ea7\u6807\u7cfb-\u7eac\u5ea6'),
        ),
        migrations.AlterField(
            model_name='bicyclestation',
            name='bdlon',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='\u767e\u5ea6\u5ea7\u6807\u7cfb-\u7ecf\u5ea6'),
        ),
        migrations.AlterField(
            model_name='bicyclestation',
            name='lat',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='\u706b\u661f\u5ea7\u6807\u7cfb-\u7eac\u5ea6'),
        ),
        migrations.AlterField(
            model_name='bicyclestation',
            name='lon',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='\u706b\u661f\u5ea7\u6807\u7cfb-\u7ecf\u5ea6'),
        ),
        migrations.AlterField(
            model_name='bicyclestation',
            name='updatetime',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='bdlat',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='\u767e\u5ea6\u5ea7\u6807\u7cfb-\u7eac\u5ea6'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='bdlon',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='\u767e\u5ea6\u5ea7\u6807\u7cfb-\u7ecf\u5ea6'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='lat',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='\u706b\u661f\u5ea7\u6807\u7cfb-\u7eac\u5ea6'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='lon',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='\u706b\u661f\u5ea7\u6807\u7cfb-\u7ecf\u5ea6'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='updatetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
